spring:
  main:
    allow-bean-definition-overriding: true

  logging:
    level:
      org:
        springframework:
          cache: TRACE

  jpa:
    show-sql: true
    hibernate:
      show_sql: true
      format_sql: true

  h2:
    console:
      enabled: true

#  cache:
#    type: redis

  redis:
    host: localhost
    port: 6379

management:
  endpoints:
    web:
      exposure:
        include: "*"
#    jmx:
#      exposure:
#      include: "*"
#      exclude: "env,beans"

springdoc:
  api-docs:
    path: /api-docs

hibernate:
    globally_quoted_identifiers: true
